CREATE TABLE "vessels" (
	"id" uuid PRIMARY KEY NOT NULL,
	"ihs_lr_or_imo_vesselno" text NOT NULL,
	"vessel_name" text,
	"call_sign" text,
	"flag_effective_date" text,
	"flag_name" text,
	"group_beneficial_owner" text,
	"group_beneficial_owner_country_of_control" text,
	"group_beneficial_owner_country_of_registration" text,
	"operator" text,
	"operator_country_of_control" text,
	"operator_country_of_registration" text,
	"registered_owner" text,
	"registered_owner_country_of_control" text,
	"registered_owner_country_of_registration" text,
	"vessel_manager" text,
	"vessel_manager_country_of_control" text,
	"vessel_manager_country_of_registration" text,
	"vesseltype_group" text,
	"comments" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
