export const statcodeToShiptypeMap = new Map([
  ["A11", "Liquefied Gas Tankers"],
  ["A12", "Chemical Tankers"],
  ["A13", "Oil Tankers"],
  ["A14", "Other Liquids Tankers"],
  ["A21", "Bulk Dry"],
  ["A22", "Bulk Dry/Oil"],
  ["A23", "Self Discharging Bulk Dry"],
  ["A24", "Other Bulk Dry"],
  ["A31", "General Cargo"],
  ["A32", "Passenger/General Cargo"],
  ["A33", "Container"],
  ["A34", "Refrigerated Cargo"],
  ["A35", "Ro-Ro Cargo"],
  ["A36", "Passenger/General Cargo"],
  ["A37", "Passenger"],
  ["A38", "Other Dry Cargo"],
  ["B11", "Fish Catching"],
  ["B12", "Other Fishing"],
  ["B21", "Offshore Supply"],
  ["B22", "Other Offshore"],
  ["B31", "Research"],
  ["B32", "Towing/Pushing"],
  ["B33", "Dredging"],
  ["B34", "Other Activities"],
  ["B35", "Other Activities"],
  ["X11", "Non Merchant Ships"],
  ["Y11", "Non Propelled Barge"],
  ["W11", "Non Seagoing Tanker"],
  ["W12", "Non Seagoing Dry Cargo/Passenger"],
  ["W13", "Other Non Seagoing"],
  ["Z11", "Non Ship Structures"],
]);
