export const statcodeToShiptypeMap = new Map([
  ["A11A", "LNG Tanker"],
  ["A11B", "LPG Tanker"],
  ["A11C", "Tanker"],
  ["A12", "Chemical Tanker"],
  ["A13", "Tanker"],
  ["A14", "Tanker"],
  ["A2", "Bulk Carrier"],
  ["A31", "General Cargo"],
  ["A32", "General Cargo"],
  ["A33", "Container"],
  ["A34", "Refrigerated Cargo"],
  ["A35", "Ro-Ro Cargo"],
  ["A36", "Passenger"],
  ["A37", "Passenger"],
  ["A38", "Other Dry Cargo"],
  ["B", "Work Vessel"],
  ["X11", "Non Merchant Ship"],
  ["Y11", "Barge"],
  ["W1", "Non Seagoing Merchant Ship"],
  ["Z11", "Non Ship Structures"],
]);
