export const statcodeToShiptypeMap = new Map([
  ["A11A", "LNG Tanker"],
  ["A11B", "LPG Tanker"],
  ["A11C", "Tanker"],
  ["A12", "Chemical Tanker"],
  ["A13", "Tanker"],
  ["A14", "Tanker"],
  ["A2", "Bulk Carrier"],
  ["A31", "General Cargo"],
  ["A32", "General Cargo/Passenger"],
  ["A33", "Container"],
  ["A34", "Refrigerated Cargo"],
  ["A35", "Ro-Ro Cargo"],
  ["A36", "Passenger"],
  ["A37", "Passenger"],
  ["A38", "Other Dry Cargo"],
  ["B11", "Fish Catching"],
  ["B12", "Other Fishing"],
  ["B21", "Offshore Supply"],
  ["B22", "Other Offshore"],
  ["B31", "Research"],
  ["B32", "Towing/Pushing"],
  ["B33", "Dredging"],
  ["B34", "Other Activities"],
  ["B35", "Other Activities"],
  ["X11", "Non Merchant Ships"],
  ["Y11", "Non Propelled Barge"],
  ["W11", "Non Seagoing Tanker"],
  ["W12", "Non Seagoing Dry Cargo/Passenger"],
  ["W13", "Other Non Seagoing"],
  ["Z11", "Non Ship Structures"],
]);
