/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VesselImoRouteImport } from './routes/vessel.$imo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VesselImoRoute = VesselImoRouteImport.update({
  id: '/vessel/$imo',
  path: '/vessel/$imo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vessel/$imo': typeof VesselImoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vessel/$imo': typeof VesselImoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vessel/$imo': typeof VesselImoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vessel/$imo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vessel/$imo'
  id: '__root__' | '/' | '/vessel/$imo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VesselImoRoute: typeof VesselImoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vessel/$imo': {
      id: '/vessel/$imo'
      path: '/vessel/$imo'
      fullPath: '/vessel/$imo'
      preLoaderRoute: typeof VesselImoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VesselImoRoute: VesselImoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
